name: AlkaSkills
version: 0.0.7-SNAPSHOT
description: AlkaSkills
main: net.alkaonline.alkaskills.AlkaSkills
depend: [kotlinbukkit, WorldGuard, WorldEdit, BungeeTabListPlus]
api-version: 1.15
commands:
  skills: {}
  giveexp: {}
  setlevel: {}
  clearskills: {}
  playerinfo: {}
  hottime: {}
  saveinfo: {}
  givepercentageexp: {}
  #addorepopulator: {}
